[project]
name = "copilot-toolkit"
version = "0.2.1"
description = "🚀 A toolkit for coding agents 🚀 Get the most out of GitHub Copilot, Cursor and Co. Powered by flock."
readme = "README.md"
authors = [
    { name = "Andre Ratzenberger", email = "andre.ratzenberger@whiteduck.de" }
]
requires-python = ">=3.10"
dependencies = [
    "flock-core>=0.3.23",
    "rich>=13.9.4",
    "tomli>=2.0.1",
]

[project.scripts]
copilot-toolkit = "copilot_toolkit:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
